@host = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJHYW1lciIsImp0aSI6ImI0ODYyZjUzLTg4ODMtNDM2ZC1iYzQxLTM1N2QwMGMzMWVjNyIsInVzZXJJZCI6IjEwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxMCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IjIiLCJleHAiOjE3NDgxOTA0MjQsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.FA0NDWtajxWaog1_rDP794d5Sp2V3p9J3lrwpnvUyHc
@admin_token = 

### 1. Роли ###
### Создать роль
POST http://localhost:5000/api/roles
Content-Type: application/json

"User"

### Получить все роли
GET http://localhost:5000/api/roles

### 2. Пользователи ###
### Регистрация
POST {{host}}/api/users/register
Content-Type: application/json

{
  "login": "Gamer",
  "password": "Password",
  "roleId": 2
}

### Авторизация
### 3. Авторизация обычного пользователя
POST {{host}}/api/users/login
Content-Type: application/json

{
  "login": "Gamer",
  "password": "Password"
}

### 3. Профили ###
### Обновить профиль
PUT https://localhost:7135/api/profiles/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFdWdlbmUiLCJqdGkiOiI5MTdkZjI4Yi03MzZlLTRiMTItYmI2Yi1hZTI4MDBlMmNhNjAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiIzIiwiZXhwIjoxNzQ4MTc0MjMyLCJpc3MiOiJ5b3VyX2lzc3VlciIsImF1ZCI6InlvdXJfYXVkaWVuY2UifQ.cwtAOz573QMNOMtBBTML2NdiioBwMK5Ju9A4Ev9aCIQ
Content-Type: application/json
{
  "fullName": "Артем 1488",
  "email": "Krakovcev@example.com",
  "institution": "Sibsutis",
  "FieldOfExpertise": "privet"
}

###

GET https://localhost:7135/api/profiles
Authorization: Bearer {{token}}

### 4. Статьи ###
### Создать статью
POST https://localhost:7135/api/articles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Новая статья",
  "authorId": 7,
  "title": "",
  "category": "Mathematics",
  "body": "Текст статьи...",
  "tags": "1258125897215",
  "status": "draft"
}

###

GET http://localhost:5000/api/articles/user/5
Authorization: Bearer {{token}}

###Отправить на рецензирование
POST https://localhost:7135/api/articles/1/submit
Authorization: Bearer {{token}}

### 5. Рецензии ###
### Создать рецензию
POST https://localhost:7135/api/reviews
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "articleId": 4,
  "reviewerId": 10,
  "comments": "Отличная статья!"
}

### Завершить рецензию
POST https://localhost:7135/api/reviews/1/complete
Content-Type: application/json

5

### 6. Файлы ###
### Загрузить файл
POST https://localhost:7135/api/files/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.txt"

< ./test.txt
--boundary--

### Прикрепить к статье
POST {{host}}/api/files/1/attach/article/1